apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: python:3.11-slim
        command:
        - /bin/sh
        - -c
        - |
          pip install flask==2.3.3
          cat > /app.py << 'PYEOF'
          from flask import Flask
          import os
          app = Flask(__name__)
          
          @app.route('/')
          def hello():
              return f"Hello from Python Pod! Hostname: {os.environ.get('HOSTNAME', 'unknown')}"
          
          @app.route('/health')
          def health():
              return {"status": "healthy"}
          
          if __name__ == '__main__':
              app.run(host='0.0.0.0', port=8080)
          PYEOF
          python /app.py
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
