apiVersion: v1
kind: Service
metadata:
  name: faulty-service
  namespace: default
spec:
  selector:
    app: wrong-app-label  # Wrong selector - won't match any pods
  ports:
  - port: 80
    targetPort: 9999     # Wrong target port
    name: http
  type: LoadBalancer     # Will remain pending in most local clusters
